products:
  check-plugin:
    build:
      main-pkg: .
      version-var: github.com/palantir/okgo/cmd.Version
      environment:
        CGO_ENABLED: "0"
      os-archs:
        - os: darwin
          arch: arm64
    dist:
      disters:
        os-arch-bin:
          type: os-arch-bin
          config:
            os-archs:
            - os: darwin
              arch: arm64
    publish: {}
product-defaults:
  publish:
    group-id: com.palantir.okgo
