products:
  okgo-plugin:
    build:
      main-pkg: .
      environment:
        CGO_ENABLED: "0"
      os-archs:
        - os: darwin
          arch: amd64
        - os: linux
          arch: amd64
group-id: com.palantir.okgo
